FROM node:22-alpine3.19
RUN apk add nginx
RUN mkdir -p /opt/mgt_app
WORKDIR /opt/mgt_app
COPY index.html package-lock.json package.json vite.config.js ./
COPY nginx_dev.conf /etc/nginx/http.d/default.conf
COPY public ./public
COPY src/ ./src
RUN npm install
EXPOSE 8080
CMD ["sh", "-c", "npm run dev -- --port 5173; nginx -g daemon off;"]