FROM node:22-alpine3.19 AS app
RUN mkdir -p /opt/mgt_app
WORKDIR /opt/mgt_app
COPY index.html package-lock.json package.json vite.config.js ./
COPY public ./public
COPY src/ ./src
RUN npm install \
    && npm run build

FROM nginx:stable-perl
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=app /opt/mgt_app/dist /usr/share/nginx/html
