FROM node:22-alpine3.19
RUN apk add nginx
RUN mkdir -p /opt/mgt_app
WORKDIR /opt/mgt_app
COPY index.html package-lock.json package.json vite.config.js ./
COPY nginx_dev.conf /etc/nginx/conf.d/default.conf
COPY public ./public
COPY src/ ./src
RUN npm install
CMD ["nginx", "-g", "daemon off;"]
CMD npm run dev -- --port 5173 --host
