FROM node:22-alpine3.19
RUN mkdir -p /opt/mgt_app
WORKDIR /opt/mgt_app
COPY index.html package-lock.json package.json vite.config.js ./
COPY public ./public
COPY src/ ./src
RUN npm install
EXPOSE 5173
ENTRYPOINT ["npm","run", "dev","--", "--port 5173"]
