---
name: Deploy
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - prod
          - dev

      clean_docker:
        type: boolean
        description: 'Remove all docker images and voluems'
        required: false
        default: false
env:
  NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

jobs:
  Build_docker_image:
    runs-on: self-hosted
    environment: ${{ inputs.job_environment }}
    steps:
      - name: Clean old Docker images
        if: "${{ inputs.clean_docker == true }}"
        run: docker system prune -a -f

      - name: Login to Docker Repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ vars.REPO }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile_${{ inputs.job_environment }}
          # yamllint disable-line rule:line-length
          tags: ${{ vars.REPO }}/${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}_${{ inputs.job_environment }}:${{ github.run_number }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_PASSWORD }}

      - name: Check image by Anchore
        # yamllint disable-line rule:line-length
        run: grype  ${{ vars.REPO }}/${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}_${{ inputs.job_environment }}:${{ github.run_number }}

  Render_template:
    needs: [Build_docker_image]
    runs-on: self-hosted
    steps:
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        env:
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          TF_VAR_REPO: ${{ vars.REPO }}
          TF_VAR_VERSION: ${{ github.run_number }}
          TF_VAR_JOB_ENV: ${{ inputs.job_environment }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          TF_VAR_REPO: ${{ vars.REPO }}
          TF_VAR_VERSION: ${{ github.run_number }}
          TF_VAR_JOB_ENV: ${{ inputs.job_environment }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          TF_VAR_REPO: ${{ vars.REPO }}
          TF_VAR_VERSION: ${{ github.run_number }}
          TF_VAR_JOB_ENV: ${{ inputs.job_environment }}

  Run_nomad:
    needs: [Render_template]
    runs-on: self-hosted
    steps:
      - name: Nomad_validate
        run: nomad job validate pm_nomad_${{ inputs.job_environment }}.nomad

      - name: Nomad_Plan
        run: |
          nomad job plan -no-color pm_nomad_${{ inputs.job_environment }}.nomad | tee /dev/stderr \
          | grep 'Job Modify Index:' | awk -F': ' '{ print $2 }'

      - name: Save_job_index
        run: |
          echo "index1=$(nomad job plan -no-color pm_nomad_${{ inputs.job_environment }}.nomad | grep 'Job Modify Index:' \
          | awk -F': ' '{ print $2 }' >> $GITHUB_ENV

      - name: Nomad_run
        id: nomad_run
        run: nomad job run -check-index "${{ env.index1 }}" pm_nomad_${{ inputs.job_environment }}.nomad
