---
name: Deploy
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - prod
          - dev

      clean_docker:
        type: boolean
        description: 'Remove all docker images and voluems'
        required: false
        default: false

jobs:
  Build_docker_image:
    runs-on: self-hosted
    environment: ${{ inputs.job_environment }}
    steps:
      - name: Clean old Docker images
        if: "${{ inputs.clean_docker == true }}"
        run: docker system prune -a -f

      - name: Login to Docker Repository
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ vars.REPO }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:docker"
          tags: ${{ vars.REPO }}/${{ secrets.DOCKER_USERNAME }}/pm_app:${{ github.run_number }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_PASSWORD }}

      - name: Check image by Anchore
        run: |
          grype  ${{ vars.REPO }}/${{ secrets.DOCKER_USERNAME }}/pm_app:${{ github.run_number }}

  Start_docker:
    needs: [Build_docker_image]
    runs-on: [self-hosted]
    environment: ${{ inputs.job_environment }}
    steps:
      - name: Run docker dev
        run: docker run ${{ vars.REPO }}/${{ secrets.DOCKER_USERNAME }}/pm_app:${{ github.run_number }} dev
        if: ${{ inputs.job_environment == dev }}
      
      - name: Run docker prod
        run: docker run ${{ vars.REPO }}/${{ secrets.DOCKER_USERNAME }}/pm_app:${{ github.run_number }} build
        if: ${{ inputs.job_environment == prod }}
